{% set name = 'freetds' %}
{% set version = "1.3.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: ftp://ftp.freetds.org/pub/freetds/stable/freetds-{{ version }}.tar.gz
  sha256: ebeb9060bcfe54f13ab0fbf8cb72ac95cc6cefbe728a30247516d55334d66a03

build:
  number: 1

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - pkg-config
  host:
    - openssl
    - unixodbc  # [not win]
    - libiconv
    - readline  # [not win]
  run:
    - openssl
    - unixodbc  # [not win]
    - readline  # [not win]

test:
  commands:
    - tsql -C

about:
  home: http://www.freetds.org/
  license: GPL-2
  license_file: COPYING
  summary: FreeTDS is a free implementation of Sybase's DB-Library, CT-Library, and ODBC libraries
  license_family: GPL2
  doc_url: http://www.freetds.org/docs.html
  dev_url: https://github.com/FreeTDS/freetds

extra:
  recipe-maintainers:
    - mariusvniekerk
    - xhochy
